server {
    listen 80;

    # Serve static files for Frontend
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Định tuyến API siêu tối giản, không can thiệp Header
    location /api/ {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        
        # Chỉ giữ lại các header định danh cơ bản nhất để tránh lỗi payload rỗng
        proxy_set_header Content-Type "application/json";
        proxy_set_header X-Real-IP $remote_addr;
    }
}