name: "App Build & Deploy Pipeline"

on:
  push:
    branches:
      - main
    paths:
      - 'app/**' # Trigger when have changes in code Frontend or Backend

env:
  AWS_REGION: "us-east-1"
  ECR_REGISTRY: "222634368199.dkr.ecr.us-east-1.amazonaws.com"

jobs:
  build-and-deploy:
    name: "Build and Deploy App"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # ---- BUILD & PUSH BACKEND ----
      - name: Build & Push Backend
        run: |
          cd app/backend
          docker build -t ${{ env.ECR_REGISTRY }}/todo-backend:final-fix .
          docker push ${{ env.ECR_REGISTRY }}/todo-backend:final-fix

      # ---- BUILD & PUSH FRONTEND ----
      - name: Build & Push Frontend
        run: |
          cd app/frontend
          npm install
          npm run build
          docker build -t ${{ env.ECR_REGISTRY }}/todo-frontend:final-fix .
          docker push ${{ env.ECR_REGISTRY }}/todo-frontend:final-fix

      # ---- END OLD TASK, FORCE ECS PULL NEW IMAGE  ----
      - name: Force New ECS Deployment
        run: |
          aws ecs update-service --cluster todo-app-cluster --service todo-app-service --force-new-deployment