name: "Terraform CI/CD Pipeline"

# Trigger the pipeline on pushes or pull requests to the main branch
on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**' # Triggers only when changes occur in the root-level terraform directory
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'

# Define common environment variables for` the workflow
env:
  AWS_REGION: "us-east-1"
  TF_WORKING_DIR: "terraform" # Points to the root-level terraform directory

jobs:
  # Job 1: Terraform Plan (Checks and previews infrastructure changes)
  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1..0" # Adjust this to match your local Terraform version

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true # Continues even if formatting has issues, but highlights them

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -out=tfplan
        continue-on-error: true # Allows the pipeline to capture the failure status in the next step

      # Stop the pipeline if the Plan step fails
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

  # Job 2: Terraform Apply (Executes changes only on push/merge to main)
  terraform-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.0" # Adjust this to match your local Terraform version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve